name: Checks

on:
  pull_request: { branches: [main] }
  push: { branches: [main] }

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Nix
        uses: nixbuild/nix-quick-install-action@v16
      - name: Install dependencies
        run: nix develop -i -c true
      - name: Check formatting
        run: nix develop -i -c npm run format-check
