name: Publish

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Nix
        uses: nixbuild/nix-quick-install-action@v16
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Install dependencies
        run: nix develop -i -c npm ci

      - name: Build & Package
        run: nix develop -i -c npm run package

      - name: Upload distribution and create tags
        uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
